// src/angular/app/components/card.component.ts
import {Component} from '@angular/core';
import USER from '../../../common/constants/USER.json';
import LABELS from '../../../common/constants/LABELS.json';
import 'common/less/card.less';
import {User, Sort} from '../Types.js';
import {Store, select} from '@ngrx/store';
import * as fromUsers from '../store/reducers/users.reducer';
import {Users} from '../store/models/users.model.js';
import {GetUsers, SortUsers} from '../store/actions/users.action';
import {Observable} from 'rxjs';

@Component({
  template: require('./card.component.html'),
})
export class CardComponent {
  USER = USER;
  LABELS = LABELS;
  items = Object.keys(USER);
  ghosts = Array(6);
  users$: Observable<User[]>;
  sort$: Observable<Sort>;
  indicator = false;

  ngOnInit() {
    this.sort$ = this.store.pipe(select(fromUsers.getSort));
    this.users$ = this.store.pipe(select(fromUsers.getList));
    this.sort$.subscribe((sort) => this.store.dispatch(new GetUsers({sort})));
  }

  execSort(key: string) {
    this.indicator = true;

    setTimeout(() => {
      this.store.dispatch(new SortUsers({key}));
      this.indicator = false;
    }, 0);
  }

  removeUser(userId: string) {}

  constructor(private store: Store<Users>) {}
}

<div class="card-container">
  <div *ngFor="let user of users$ | async">
    <p *ngFor="let item of items" [ngClass]="item" [attr.data-test]="user[item]">
      <ng-container *ngIf="item !== 'gender' && item !== 'authority'">{{user[item]}}</ng-container>
      <span *ngIf="item === 'gender'" [ngClass]="user[item]"></span>
      <span *ngIf="item === 'authority'" [ngClass]="user[item]" [attr.title]="user[item]"></span>
    </p>
    <span class="remove" [attr.title]="LABELS.REMOVE_USER" (click)="removeUser(user.id)"></span>
  </div>
  <div class="ghost" *ngFor="let ghost of ghosts"></div>
</div>
<div class="sorter">
  <span *ngFor="let item of items" [class.sorted]="item === (sort$ | async).key" (click)="execSort(item)">
    <span *ngIf="item === (sort$ | async).key" class="icon" [ngClass]="(sort$ | async).order"></span>
    {{USER[item].label}}
  </span>
</div>
<div class="indicator" *ngIf="indicator"></div>

// src/vue/component/Card.vue
<template>
  <div style="position: relative;" :style="styles">
    <div class="card-container">
      <div v-for="user in users" :key="user.id">
        <p v-for="item in items" :key="item" :class="item">
          <template v-if="item !== 'gender' && item !== 'authority'">{{user[item]}}</template>
          <span v-if="item === 'gender'" :class="user[item]"></span>
          <span v-if="item === 'authority'" :class="user[item]" :title="user[item]"></span>
        </p>
        <span class="remove" :title="LABELS.REMOVE_USER" @click="removeUser(user.id)"></span>
      </div>
      <div class="ghost" v-for="(ghost, i) in Array(6)" :key="i"></div>
    </div>
    <div class="sorter">
      <span
        v-for="item in items"
        :key="item"
        :class="{sorted: sort.key === item}"
        @click="execSort(item)"
      >
        <span v-if="item === sort.key" class="icon" :class="sort.order"></span>
        {{USER[item].label}}
      </span>
    </div>
    <div class="indicator" v-show="indicator"></div>
  </div>
</template>

<script>
import 'vue-style-loader?modules!common/less/card.less';
import USER from 'common/constants/USER.json';
import LABELS from 'common/constants/LABELS.json';
import {mapState} from 'vuex';
import ActionTypes from '../store/actions';

export default {
  data() {
    return {
      USER: USER,
      LABELS: LABELS,
      items: Object.keys(USER),
      indicator: false,
    };
  },
  props: ['styles'],
  computed: mapState({
    users: state => state.users.list,
    sort: state => state.users.sort,
  }),
  methods: {
    execSort(key) {
      this.indicator = true;

      setTimeout(() => {
        this.$store.dispatch(ActionTypes.SORT_USERS, key);
        this.indicator = false;
      }, 50);
    },
    removeUser(userId) {
      this.$store.dispatch(ActionTypes.REMOVE_USER, userId);
    },
  },
};
</script>
