// src/react/components/Switcher.jsx
import 'common/less/switcher.less';
import React, {Component} from 'react';
import {connect} from 'react-redux';
import {withRouter} from 'react-router-dom';
import LABELS from 'common/constants/LABELS.json';

class Switcher extends Component {
  switching(location) {
    this.props.history.push(`/${location}`);
  }

  render() {
    return (
      <div className="switcher">
        <span className="table" onClick={() => this.switching('table')}>
          {LABELS.TABLE_VIEW}
        </span>
        <span className="card" onClick={() => this.switching('card')}>
          {LABELS.CARD_VIEW}
        </span>
      </div>
    );
  }
}

export default withRouter(connect()(Switcher));

// src/vue/component/Switcher.vue
<template>
  <div class="switcher">
    <span @click="switching('table')" class="table">{{LABELS.TABLE_VIEW}}</span>
    <span @click="switching('card')" class="card">{{LABELS.CARD_VIEW}}</span>
  </div>
</template>

<script>
import 'vue-style-loader?modules!common/less/switcher.less';
import LABELS from 'common/constants/LABELS.json';

export default {
  data() {
    return {
      LABELS: LABELS,
    };
  },
  methods: {
    switching(mode) {
      this.$router.push(`/${mode}`);
    },
  },
};
</script>
