// src/react/components/Header.jsx
import 'common/less/header.less';
import React, {Component} from 'react';
import {connect} from 'react-redux';
import LABELS from 'common/constants/LABELS.json';
import Join from './Join';
import Switcher from './Switcher';

class Header extends Component {
  render() {
    return (
      <div style={this.props.styles}>
        <div className="header">
          <span className="back" title={LABELS.BACK_TO_TOP} onClick={() => (location.href = '/')} />
          <h1>{LABELS.HEADER_TITLE}</h1>
        </div>
        <Join />
        <Switcher />
      </div>
    );
  }
}

export default connect()(Header);

// src/angular/app/components/header.component.ts
import {Component, Input} from '@angular/core';
import LABELS from '../../../common/constants/LABELS.json';
import 'common/less/header.less';

@Component({
  selector: '[app-header]',
  template: require('./header.component.html'),
})
export class HeaderComponent {
  @Input() styles: CSSStyleDeclaration;
  LABELS = LABELS;

  backToTop(): void {
    location.href = '/';
  }
}

<div class="header">
  <span class="back" [attr.title]="LABELS.BACK_TO_TOP" (click)="backToTop()"></span>
  <h1>{{LABELS.HEADER_TITLE}}</h1>
</div>
<!-- <join></join> -->
<div app-switcher class="switcher"></div>
