// src/vue/component/Switcher.vue
<template>
  <div class="switcher">
    <span @click="switching('table')" class="table">{{LABELS.TABLE_VIEW}}</span>
    <span @click="switching('card')" class="card">{{LABELS.CARD_VIEW}}</span>
  </div>
</template>

<script>
import 'vue-style-loader?modules!common/less/switcher.less';
import LABELS from 'common/constants/LABELS.json';

export default {
  data() {
    return {
      LABELS: LABELS,
    };
  },
  methods: {
    switching(mode) {
      this.$router.push(`/${mode}`);
    },
  },
};
</script>

// src/angular/app/components/switcher.component.ts
import {Component} from '@angular/core';
import {Location} from '@angular/common';
import LABELS from '../../../common/constants/LABELS.json';
import 'common/less/switcher.less';

@Component({
  selector: '[app-switcher]',
  template: require('./switcher.component.html'),
})
export class SwitcherComponent {
  LABELS = LABELS;

  switching(mode: String) {
    this.location.go(`/${mode}`);
  }

  constructor(private location: Location) {}
}

<span (click)="switching('table')" class="table">{{LABELS.TABLE_VIEW}}</span>
<span (click)="switching('card')" class="card">{{LABELS.CARD_VIEW}}</span>
