// src/vue/component/Header.vue
<template>
  <div :style="styles">
    <div class="header">
      <span class="back" :title="LABELS.BACK_TO_TOP" @click="backToTop"></span>
      <h1>{{LABELS.HEADER_TITLE}}</h1>
    </div>
    <join></join>
    <switcher></switcher>
  </div>
</template>

<script>
import 'vue-style-loader?modules!common/less/header.less';
import LABELS from 'common/constants/LABELS.json';
import Join from './Join.vue';
import Switcher from './Switcher.vue';

export default {
  data() {
    return {
      LABELS: LABELS,
    };
  },
  props: ['styles'],
  methods: {
    backToTop() {
      location.href = '/';
    },
  },
  components: {
    join: Join,
    switcher: Switcher,
  },
};
</script>

// src/react/components/Header.jsx
import 'common/less/header.less';
import React, {Component} from 'react';
import {connect} from 'react-redux';
import LABELS from 'common/constants/LABELS.json';
import Join from './Join';
import Switcher from './Switcher';

class Header extends Component {
  render() {
    return (
      <div style={this.props.styles}>
        <div className="header">
          <span className="back" title={LABELS.BACK_TO_TOP} onClick={() => (location.href = '/')} />
          <h1>{LABELS.HEADER_TITLE}</h1>
        </div>
        <Join />
        <Switcher />
      </div>
    );
  }
}

export default connect()(Header);
