// src/angular/app/components/join.component.ts
import {Component} from '@angular/core';
import {FormBuilder, FormGroup} from '@angular/forms';
import {Store} from '@ngrx/store';
import * as fromUsers from '../store/reducers/users.reducer';

import USER from '../../../common/constants/USER.json';
import MESSAGES from '../../../common/constants/MESSAGES.json';
import 'common/less/join.less';
import {Users} from '../store/app.state.js';
import {UserInfoKey, User} from '../Types';
import {AppendUser} from '../store/actions/users.action';

@Component({
  selector: 'app-join',
  template: require('./join.component.html'),
})
export class JoinComponent {
  USER = USER;
  items = Object.keys(USER);
  isOpen = false;
  button = 'open';
  userInfo: User = {};
  joinForm: FormGroup;
  form: HTMLFormElement | null;

  ngOnInit() {
    this.joinForm = this.builder.group(
      this.items.reduce((acc: {[key: string]: any}, key: UserInfoKey) => {
        acc[key] = [''];
        return acc;
      }, {})
    );
  }

  ngAfterViewInit() {
    this.form = document.querySelector('[name="user-info"]');
  }

  validate(key: UserInfoKey, e: Event) {
    if (!e.target) return;

    const value = (this.userInfo[key] = (e.target as HTMLInputElement).value);

    if (key === 'id') {
      this.store$.select(fromUsers.getList).subscribe((list) => {
        if (!this.form) return;

        const element = this.form[key as string] as HTMLInputElement;
        element.setCustomValidity(list.some((user) => user.id === value) ? MESSAGES.DUPLICATED_ID : '');
      });
    }
  }

  open() {
    this.isOpen = true;
  }

  close() {
    this.isOpen = false;
    this.button = 'open';
  }

  buttonChange() {
    if (this.isOpen) {
      this.button = 'register';
    }
  }

  register() {
    if (this.form && this.form.reportValidity()) {
      this.store$.dispatch(new AppendUser({user: this.userInfo}));
      this.close();
      Object.keys(this.userInfo).forEach((key: UserInfoKey) => (this.userInfo[key] = ''));
    }
  }

  constructor(private builder: FormBuilder, private store$: Store<Users>) {}
}

<div class="join" [class.open]="isOpen" (transitionend)="buttonChange()">
  <form name="user-info" [formGroup]="joinForm" (submit)="$event.preventDefault(); $event.stopPropagation();">
    <div class="items" *ngFor="let item of items">
      <span *ngIf="USER[item].require" class="require">*</span>
      <label>{{USER[item].label}}</label>
      <input (input)="validate(item, $event)" [formControlName]="item" [attr.name]="item"
        [required]="USER[item].require ? 'required' : null">
    </div>
  </form>
  <div class="btn-join" (mousedown)="open()" *ngIf="button === 'open'"></div>
  <div class="btn-register" *ngIf="button === 'register'">
    <span class="cancel" (mousedown)="close()"></span>
    <span class="register" (click)="register()"></span>
  </div>
</div>

// src/react/components/Join.jsx
import 'common/less/join.less';
import React, {Component} from 'react';
import {connect} from 'react-redux';
import classnames from 'classnames';
import USER from 'common/constants/USER.json';
import MESSAGES from 'common/constants/MESSAGES.json';
import * as ActionCreators from '../actionCreators';

class Join extends Component {
  constructor(props) {
    super(props);

    this.state = {
      button: 'open',
      isOpen: false,
    };
  }

  componentWillMount = () => {
    this.items = Object.keys(USER);
  };

  componentDidUpdate = () => {
    this.form = document.forms['user-info'];
  };

  buttonChange = (e) => {
    if (e.currentTarget !== e.target) return;
    if (this.state.isOpen) {
      this.setState({button: 'register'});
    }
  };

  open = () => {
    this.setState({isOpen: true});
  };

  close = () => {
    this.setState({
      isOpen: false,
      button: 'open',
    });
  };

  validate = (key, e) => {
    if (key === 'id') {
      if (this.props.state.users.list.some((user) => user.id === e.target.value)) {
        this.form[key].setCustomValidity(MESSAGES.DUPLICATED_ID);
      } else {
        this.form[key].setCustomValidity('');
      }
    }
  };

  register = (e) => {
    if (this.form.reportValidity()) {
      const userInfo = {};
      this.items.forEach((item) => {
        userInfo[item] = this.form[item].value;
      });

      this.props.dispatch(ActionCreators.appendUser(userInfo));
      this.close();
    }
  };

  render() {
    const UserForm = () => {
      return (
        <form name="user-info" onSubmit={(e) => (e.stopPropagation(), e.preventDefault())}>
          {this.items.map((item) => {
            const validationAttrs = {};
            USER[item].require && (validationAttrs.required = 'required');

            return (
              <div className="items" key={item}>
                {USER[item].require && <span className="require">*</span>}
                <label>{USER[item].label}</label>
                <input onInput={(e) => this.validate(item, e)} name={item} {...validationAttrs} />
              </div>
            );
          })}
        </form>
      );
    };

    const joinClasses = classnames({
      join: true,
      open: this.state.isOpen,
    });

    return (
      <div className={joinClasses} onTransitionEnd={this.buttonChange}>
        <UserForm />
        {this.state.button === 'open' && <div className="btn-join" onMouseDown={this.open} />}
        {this.state.button === 'register' && (
          <div className="btn-register">
            <span className="cancel" onMouseDown={this.close} />
            <span className="register" onClick={this.register} />
          </div>
        )}
      </div>
    );
  }
}

function mapStateToProps(state) {
  return {state};
}

export default connect(mapStateToProps)(Join);
